force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>courseId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>dateCompleted__c</fullName>
        <label>Completed date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dateEnrolled__c</fullName>
        <label>Enrollment date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course enrollment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Enrollment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SearchEnrollment.cls
//Apex controller file to search the enrollment based on user/contact details
public with sharing class SearchEnrollment {
    //The @AuraEnabled annotation exposes this method to SearchEnrollment and other lightning components
    @AuraEnabled
    public static List<Enrolment__c> searchEnrollments(String searchTerm) {
        String searchKey = searchTerm + '%';
        List<Enrolment__c> returnList = new List<Enrolment__c>();
        
        //First search the student for the given email, name or username
        Student__c[] stds = [SELECT Id, Name__c, Email__c, Username__c from Student__c WHERE Name__c LIKE: searchKey OR Email__c LIKE: searchKey OR Username__c LIKE: searchKey];
        if(stds.size() > 0) {
        //Then, search the enrollment details for the fetched student 
        String enrollmentQuery = 'SELECT Id, dateCompleted__c,dateEnrolled__c,Name,status__c, Course__r.Name__c FROM Enrolment__c WHERE Student__c= \'';
        enrollmentQuery += stds[0].Id+'\'';
        enrollmentQuery += ' ORDER BY Name  ASC, CreatedDate DESC';        
        system.debug('enrollmentQuery ==>'+enrollmentQuery );          
        returnList = Database.query(enrollmentQuery);       
        }
        //Return enrollment list to the component
        return returnList;
        
    }
}