force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Student.cls
global class Student {
    
public static void studAdd(Set<Id> userIds) {

List<User> user = [select Id, firstname, lastname, Username, email from user where Id IN :userIds];

List<Student__c> studToUpdate = new List<Student__c>();

for (User usr : User) {

Student__c stud = new Student__c (
Username__c = usr.Username,   

FirstName__c = usr.FirstName,

Email__c = usr.Email,

LastName__c = usr.LastName,

Name__c = usr.FirstName + ' ' + usr.LastName,

Type__c = 'User'
);

studToUpdate.add(stud);

}

insert studToUpdate;

}

    
public static void studAddFromContact(Set<Id> contactIds) {

List<Contact> Contacts = [select Id, firstname, lastname, email from Contact where Id IN :contactIds];

List<Student__c> studToUpdate = new List<Student__c>();

for (Contact contact : Contacts) {

Student__c stud = new Student__c (

/* Since contact doesn't have the username field, copying email value to student's username value */    
Username__c = contact.Email,
    
FirstName__c = contact.FirstName,

Email__c = contact.Email,

LastName__c = contact.LastName,

Name__c = contact.FirstName + ' ' + contact.LastName,

Type__c = 'Contact'
);

studToUpdate.add(stud);

}

insert studToUpdate;

}
    
}